### ISSUE TITLE
Vygenerovaný kalendář je prázdný

### ISSUE THREAD

**Issue by pavelmaca** [drml/rozvrhar#1]
Výstupní iCal soubor neobsahuje žádnou akci.

![vyplneni](https://cloud.githubusercontent.com/assets/276292/22654141/22be7f3e-ec8c-11e6-9bbf-14051bcb25f7.JPG)

Obsah souboru:
```ical
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-TIMEZONE:Europe/Prague
BEGIN:VTIMEZONE
TZID:Europe/Prague
X-LIC-LOCATION:Europe/Prague
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by drml** [comment]
Fixed.

IS STAG bere parametr rok jako první ze dvojice akademického roku (např. pro letošní letní semestr je potřeba zadat 2016, protože spadá do akademického roku **2016**/2017).  UI upraveno, aby tato vlastnost byla jasněji zřejmá. Pro větší komfort se navíc nyní rok a semestr automaticky předvyplní podle aktuálního data.

![image](https://cloud.githubusercontent.com/assets/5463003/22658532/bb037a48-ec9a-11e6-98bc-d06f6864b60d.png)
